QUESTIONS = [{'question': 'Q1:What is the capital of France?',
              'option1': 'Paris', 'option2': 'Berlin', 'option3': 'Madrid',
              'correctanswer': '1'},
             {'question': 'Q2:What is the largest ocean in the world?',
              'option1': 'Atlantic Ocean', 'option2': 'Pacific Ocean',
              'option3': 'Indian Ocean', 'correctanswer': '2'},
             {'question': 'Q3:What is the capital of Australia?',
              'option1': 'Sydney',
              'option2': 'Canberra',
              'option3': 'Melbourne',
              'correctanswer': '2'},
             {'question': 'Q4:What is the currency of Japan?',
              'option1': 'Dollar',
              'option2': 'Pound',
              'option3': 'Yen',
              'correctanswer': '3'},
             {'question': 'Q5:What is the tallest mountain in the world?',
              'option1': 'K2',
              'option2': 'Mount Everest',
              'option3': 'Lhotse',
              'correctanswer': '2'},
             {'question': 'Q6:What is the most populous city in the world?',
              'option1': 'Beijing',
              'option2': 'Istanbul',
              'option3': 'Mumbai',
              'correctanswer': '1'},
             {'question': 'Q7:What is the largest planet in the solar system?',
              'option1': 'Earth',
              'option2': 'Mars',
              'option3': 'Jupiter',
              'correctanswer': '3'},
             {'question': 'Q8:What theory explains the origin of universe?',
              'option1': 'Evolution',
              'option2': 'General Relativity',
              'option3': 'Big Bang Theory',
              'correctanswer': '3'}]
